[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["galim-kang <togarim@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
