[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["galim-kang <togarim@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.3"
pillow = "^10.0.0"
django-rest-framework = "^0.1.0"
django-cors-headers = "^4.2.0"




[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
