# Generated by Django 4.2.3 on 2023-07-16 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiter',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
